import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Nav from "./components/Nav";
import Subscribe from "./components/Subscribe";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ShopCenter - A E-commerce website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <Header />
        <main>
          {children}
          <Subscribe />
        </main>
        <Footer />
      </body>
    </html>
  );
}
